-- OGRS Farming skill — add the per-skill column to every table the dynamic
-- SQL builder iterates over.
--
-- See 2026_05_06_add_slayer_skill.sql for the same pattern. Each ALTER
-- wrapped in its own stored procedure with CONTINUE HANDLER so the patch
-- is idempotent.

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `_PREFIX_experience` ADD COLUMN `farming` INT(9) NOT NULL DEFAULT 0;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `_PREFIX_curstats` ADD COLUMN `farming` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `_PREFIX_maxstats` ADD COLUMN `farming` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `_PREFIX_capped_experience` ADD COLUMN `farming` INT(10) UNSIGNED;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
